// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXgyFKtYLB9LIyI-z_mQSq13D-r852ydU',
    appId: '1:767880661683:web:342812a53328ac79ce3ec6',
    messagingSenderId: '767880661683',
    projectId: 'financas-flutter-ad604',
    authDomain: 'financas-flutter-ad604.firebaseapp.com',
    storageBucket: 'financas-flutter-ad604.appspot.com',
    measurementId: 'G-Z50LMF42G5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzf9AGBrTpjdtp9IgGDfDP_ORsIHDg2Xg',
    appId: '1:767880661683:android:603670110e69814bce3ec6',
    messagingSenderId: '767880661683',
    projectId: 'financas-flutter-ad604',
    storageBucket: 'financas-flutter-ad604.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI6IMH-6L4Bp-79U_gw9NYeHdYXtfhyeY',
    appId: '1:767880661683:ios:7309893f2919b5f7ce3ec6',
    messagingSenderId: '767880661683',
    projectId: 'financas-flutter-ad604',
    storageBucket: 'financas-flutter-ad604.appspot.com',
    iosBundleId: 'com.example.financasPessoais',
  );
}
